<?php /* $Id$ */

/**
 * @file Component module for sending Mime-encoded emails
 * 
 */
 
/**
 * Implementation of hook_help()
 */
function mimemail_help($section) {
  switch($section) {
    
    case 'admin/modules#description' :
      return t('Mime Email');
      
    default :
      return;
  }
}

/**
 * Implementation of hook_settings()
 */
function mimemail_settings() {
  $engines = mimemail_get_engines();
  
  $form = array();
  $form['site_mail'] = array(
      '#type'          => 'textfield', 
      '#title'         => t('E-mail address'), 
      '#default_value' => variable_get('site_mail', ini_get('sendmail_from')), 
      '#size' => 60, 
      '#maxlength' => 128, 
      '#description' => t('A valid e-mail address for this website, used by the auto-mailer during registration, new password requests, notifications, etc.')
  );
  $form['mimemail']['mimemail_textonly'] = array(
    '#type'           => 'checkbox',
    '#title'           => t('Plaintext email only'),
    '#default_value'   => variable_get('mimemail_textonly', 0),
    '#description'     => t('This option disables the use of email messages with graphics and styles.  All messages will be converted to plain text.'),
  );
  
  // hide the settings if only 1 engine is available
  if (count($engines == 1)) {
    variable_set('mimemail_engine',key($engines));
    $form['mimemail_engine'] = array(
        '#type'          => 'hidden',
        '#title'         => t('E-mail engine'), 
        '#default_value' => variable_get('mimemail_engine', 'mail'), 
        '#options'       => $engines, 
        '#description'   => t('Choose an e-mail engine for sending mails from your site.')
    );
  }
  else {
    $form['mimemail_engine'] = array(
        '#type'          => 'select',
        '#title'         => t('E-mail engine'), 
        '#default_value' => variable_get('mimemail_engine', 'mail'), 
        '#options'       => $engines, 
        '#description'   => t('Choose an e-mail engine for sending mails from your site.')
    );
  }

  if (variable_get('mimemail_engine', 0)) {
    $settings = module_invoke(variable_get('mimemail_engine', 'mail'), 'mailengine', 'settings');
    if ($settings) {
        $form['mimemail_engine_settings'] = array(
          '#type'        => 'fieldset', 
          '#title'       => t('Engine specific settings'),
      );
      foreach ($settings as $name => $value) {
        $form['mimemail_engine_settings'][$name] = $value;
      }
    }
  }
  else {
    drupal_set_message(t('Please choose a mail engine.'), 'error');
  }
  return $form;
}

/**
 * Implementation of hook_user()
 */
function mimemail_user($op, &$edit, &$user, $category='') {
  if ( $op == 'form' && $category == 'account') { 
    $form = array();
    $form['mimemail'] = array(
        '#type'          => 'fieldset',
        '#title'         => t('Email settings'),
        '#weight'        => 5, 
        '#collapsible' => true,
    );
    $form['mimemail']['mimemail_textonly'] = array(
      '#type'           => 'checkbox',
      '#title'           => t('Plaintext email only'),
      '#default_value'   => $user->mimemail_textonly,
      '#description'     => t('Check this option if you do not wish to receive email messages with graphics and styles'),
    );
    return $form;
  } 
  return;
}

/**
 * Send a mime-encoded email
 * 
 * @param $sender The email address or user object
 * @param $recipient An email address or user object * @param $subject An subject line string
 * @param $body An HTML body
 * @param $plaintext Whether to send message as plaintext only
 * @param $headers Optional e-mail headers in a keyed array
 * @param $text Optional plaintext portion of a multipart e-mail (instead of auto-generated)
 * 
 * @return result from mail() call
 */
function mimemail($sender, $recipient, $subject, $body, $plaintext=null, $headers=array(), $text=null) {
  require_once dirname(__FILE__).'/mimemail.inc';
  
  // try to determine recpient's text mail preference
  if (!is_null($plaintext)) {
    if (is_object($recipient) && isset($recipient->mimemail_textonly)) {
      $plaintext = $recipient->mimemail_textonly;
    }
    elseif (valid_email_address($recipient)) {
      if (is_object($r = user_load(array('mail'=>$recipient))) && isset($r->mimemail_textonly)) {
        $plaintext = $r->mimemail_textonly;
        $recipient = $r; // might as well pass the user object to the address function
      }
    }
  }
  
  if (is_null($sender)) {        // use site default for sender
    $sender = array(
        'name' => variable_get('site_name', 'Drupal'),
        'mail' => variable_get('site_mail', ini_get('sendmail_from')),
    );
  }
  
  if (is_null($recipient)) {     // use site default for recipient
    $recipient = array(
        'name' => variable_get('site_name', 'Drupal'),
        'mail' => variable_get('site_mail', ini_get('sendmail_from')),
    );
  }
  
  $plaintext = $plaintext || variable_get('mimemail_textonly', 0);
  $sender    = mimemail_address($sender);
  $mail      = mimemail_html_body(theme('mimemail_message', $body), $subject, $plaintext, $text);
  $headers   = array_merge($headers, $mail['headers']);
  $message   = array(
    'address' => mimemail_address($recipient),
    'subject' => $subject,
    'body'    => $mail['body'],
    'headers' => mimemail_prepare_headers($headers, $sender),
  );
  
  $engine = variable_get('mimemail_engine', 'mimemail') .'_mailengine';
  
  if (!function_exists($engine)) {
    return false;
  }
  if (is_string($message['address'])) {
    return $engine('single', $message);
  }
  if (is_array($message['address'])) {
    return $engine('multiple', $message);
  }
  return false;
}

/**
 * Returns available mailer engines.
 *
 * @return an array of mailer engine names.
 */
function mimemail_get_engines() {
  $engines = array();
  foreach(module_implements('mailengine') as $module) {
    $function = $module .'_mailengine';
    if (function_exists($function)) {
      $engines[$module] = $function('name') .' - '. $function('description');
    }
  }
  return $engines;
}

/**
 * Default mailengine
 */
function mimemail_mailengine($op, $message = array()) {
  //default values
  $message = array_merge( array(
      'address' => '', 
      'subject' => '', 
      'body' => '', 
      'headers' => '', 
      'parameters' => ''), $message);
      
  switch ($op) {
    case 'name':
      return t('Mime Mail');
      
    case 'description':
      return t("Default mailing engine using PHP's mail().");
      
    case 'settings': //not implemented
      return false;
      
    case 'single':
      if (!$message['parameters'] || ini_get('safe_mode')) {
        return mail(
          $message['address'], 
          $message['subject'], 
          $message['body'], 
          $message['headers']
        );
      }
      return mail(
        $message['address'], 
        $message['subject'], 
        $message['body'], 
        $message['headers'],
        $message['parameters']
      );
    
    case 'multiple':
      $status = true;
      foreach ($message['address'] as $a) {
        $status = mimemail_mailengine('single', array_merge($message,array('address'=>$a))) && $status;
      }
      return $status;
    
    default: // method not implemented.
      return false;
  }
}

/**
 * Themeable message body
 */
function theme_mimemail_message($body) {
  $output = '<html><head><style type="text/css"><!--';
  // embed a version of all style definitions
  foreach (theme_add_style() as $style) {
    if (in_array($style->media, array('all', 'screen'))) {
      $output .= file_get_contents(substr($style->path, strlen(base_path())));
    }
  }
  $output .= '--></style></head><body id="mimemail-body">'.$body.'</body></html>';
  // compress output
  return preg_replace('/\s+|\n|\r|^\s|\s$/',' ',$output);
}
